version: "3.8"

services:
  rob521:
    image: rob521
    container_name: rob521_container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/ismail/code/ROB521/snowball:/home/catkin_ws/src/snowball
    network_mode: "host"
    privileged: true 
    tty: true
    command: /bin/bash


volumes:
  snowball: